### ISSUE TITLE
storing data "per trial" not working as intended?

### ISSUE THREAD

**Issue by schluppeck** [Rowanhuxnotts/RHCode#2]
@Rowanhuxnotts - i think part of the reason the data files from `psychopy` look weird is because everything is appended into one giant trial

https://github.com/Rowanhuxnotts/RHCode/blob/ce1a6022b5c178fe11183a2862a15fc10fba8fe5/TWPsychophysics/ContrastTriggers.py#L214C7-L214C36

if you look a the [documentation on `addData`](https://psychopy.org/api/data.html#:~:text=%23%20end%20of%20trial%20%2D%20move%20to%20next%20line%20in%20data%20output%0Aexp.nextEntry()) you'll see that a call to `nextEntry()` wlll move on to storing data for the next trial (in a new column.

Also need to double-check that you are using [`saveAsWideText`](https://psychopy.org/api/data.html#:~:text=saveAsWideText(fileName,%C2%B6) is used if that's the better way to go?

**Comment by Rowanhuxnotts** [comment]
Moved to a different method of storing data that avoids this issue. 

Now saves in tidy data format using csv.writer rather than trial handler which was causing the issue.
